#!/usr/local/bin/zsh
usualSuspects="vim nvim gopls godef bingo golangci-lint go-statsus"
killall $usualSuspects &>/dev/null

echo "Killing potential CPU/memory killers:"
echo $usualSuspects | xargs -n 1 -I {} echo {}✓

echo "Restarting DNS over HTTPS:"
sudo cloudflared service uninstall
sudo cloudflared service install

echo "Enjoy! :)"
