#!/bin/bash

note_path="$HOME/Jottacloud/noter"
note_title="$*"
note_filename="$note_path/$(gdate -I)_${note_title// /-}.md"
mkdir -p -v "$note_path"
touch $note_filename
echo $note_filename
echo "# $note_title" >$note_filename
echo "" >>$note_filename
echo "" >>$note_filename
vim +3 "$note_filename"
