#!/bin/bash
root_path="$HOME/Jottacloud/week"
year_path="$root_path/$(date +%Y)"
mkdir -p "$year_path"

if command -v ghead &>/dev/null; then
  function head() {
    ghead $*
  }

  function date() {
    gdate $*
  }

  function sed() {
    gsed $*
  }
fi

default_week=$(
  cat <<EOF
# Monday
- Shutdown day
# Tuesday
- Shutdown day
# Wednesday
- Shutdown day
# Thursday
- Shutdown day
# Friday
- Shutdown week
# Inbox
EOF
)

# Generate week template if none is present
week_template="$HOME/Jottacloud/week/template.md"
if [[ ! -e "$week_template" ]]; then
  echo "$default_week" >"$week_template"
fi

# Generate current week if none is present
current_week="$year_path/$(date +%U).md"
previous_week="$year_path/$(($(date +%U) - 1)).md"
if [[ ! -e "$current_week" ]]; then
  cat "$week_template" >"$current_week"

  if [[ -e "$previous_week" ]]; then
    cat "$previous_week" | grep "\[ " | sed 's/^/(Previous week) /' >>"$current_week"
  fi
fi

today="$(date +%A)"
next_day_or_inbox="$(date --date=tomorrow +%A | sed 's/Saturday/Inbox/g')"

while getopts 'ctsi:' flag; do
  case "${flag}" in
  c)
    $EDITOR "$week_template"
    exit 0
    ;;
  t)
    awk "/$today/, /$next_day_or_inbox/" "$current_week" | head -n -1 | grep -v 'Shutdown\|  '
    exit 0
    ;;
  s)
    awk "/$today/, /$next_day_or_inbox/" "$current_week" | head -n -1 | grep 'Shutdown\|  '
    exit 0
    ;;
  i)
    something="${OPTARG}"
    echo "- [ ] $something" >>"$current_week"
    echo "$something added to this week!"
    exit 0
    ;;
  *)
    echo "invalid flag"
    exit 1
    ;;
  esac
done

$EDITOR "$current_week"
